# Generated by Django 3.2.9 on 2022-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshapp', '0002_worklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shikshapp_teachers',
            old_name='username',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='worklist',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], max_length=2),
        ),
    ]
