# Generated by Django 3.2.9 on 2022-02-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
